AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-newrelic.gemspec

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Max: 147

Metrics/BlockNesting:
  Max: 4

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 406

Metrics/CyclomaticComplexity:
  Max: 24

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Layout/LineLength:
  Enabled: false

# Offense count: 63
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 88

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1000

Style/PercentLiteralDelimiters:
  Enabled: false
