version: 2.1

ruby_env: &ruby_env
  working_directory: ~/repo
  environment:
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle
    RACK_ENV: test
    RAILS_ENV: test
    RUBY_VERSION: <<parameters.ruby-version>>
  docker:
    - image: circleci/ruby:<<parameters.ruby-version>>

executors:
  ruby_2_6:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.6"
  ruby_2_7:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.7"
  ruby_3_0:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "3.0"

commands:
  pre-setup:
    steps:
      - add_ssh_keys
      - checkout
  bundle-install:
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rspec-unit:
    parameters:
      additional_args:
        type: string
        default: ""
      glob:
        type: string
        default: ""
    steps:
      - run: mkdir ~/rspec
      - run:
          name: "Run rspec tests"
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            echo "Running: ${TESTFILES}"
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml <<parameters.additional_args>> -- ${TESTFILES}
          when: always
      - store_test_results:
          path: ~/rspec
  bundle-audit:
    parameters:
      additional_args:
        type: string
        default: ""
    steps:
      - run: bundle exec bundle-audit update
      - run: bundle exec bundle-audit check -v <<parameters.additional_args>>
  rubocop:
    steps:
      - run: bundle exec rubocop -p

jobs:
  bundle-audit:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - bundle-install
      - bundle-audit
  rubocop:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - bundle-install
      - bundle-audit
  rspec-unit:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - bundle-install
      - rspec-unit

workflows:
  version: 2
  ruby_2_6:
    jobs:
      - bundle-audit:
          name: ruby_2_6-bundle_audit
          e: ruby_2_6
      - rubocop:
          name: ruby_2_6-rubocop
          e: ruby_2_6
      - rspec-unit:
          name: ruby_2_6-rspec_unit
          e: ruby_2_6
  ruby_2_7:
    jobs:
      - bundle-audit:
          name: ruby_2_7-bundle_audit
          e: ruby_2_7
      - rubocop:
          name: ruby-2_7-rubocop
          e: ruby_2_7
      - rspec-unit:
          name: ruby-2_7-rspec
          e: ruby_2_7
  ruby_3_0:
    jobs:
      - bundle-audit:
          name: ruby_3_0-bundle_audit
          e: ruby_3_0
      - rubocop:
          name: ruby_3_0-rubocop
          e: ruby_3_0
      - rspec-unit:
          name: ruby_3_0-rspec
          e: ruby_3_0
